data_dir = "/tmp"

[sources.http]
type = "http_server"
address= "0.0.0.0:${VECTOR_PORT}"

# useful for debugging locally
[sources.file]
type = "file"
include = ["/var/logs/*"]

[transforms.parse_logs]
type= "remap"
file = "${VECTOR_TRANSFORMS_PATH:-.}/transforms.vrl"
inputs = ["http","file"]


# useful for debugging locally
# [sinks.console]
# type = "console"
# encoding.codec = "json"
# inputs = ["parse_logs"]

[sinks.timescaledb]
type = "postgres"
inputs = ["parse_logs"]
endpoint = "${VECTOR_DB_URL}"
table = "logs"