apiVersion: 1

datasources:
  - name: Potentiel DB
    uid: potentiel-db
    type: postgres
    url: ${LOG_DB_HOST:log_db}:${LOG_DB_PORT:5432}
    user: ${LOG_DB_USER:postgres}
    jsonData:
      database: ${LOG_DB_NAME:postgres}
      sslmode: ${LOG_DB_SSLMODE:disable}
      postgresVersion: 1500
      timescaledb: true
    secureJsonData: {}
    isDefault: true
    editable: false
